name: shelfscout
description: A location-based competitive grocery price-hunting game.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  dio: ^5.4.3
  provider: ^6.1.2
  firebase_messaging: ^14.9.1
  firebase_core: ^2.31.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
